---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/comments":
    get:
      summary: Comment list
      tags:
      - Comments
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  current_page:
                    type: integer
                  total_pages:
                    type: integer
                  per_page:
                    type: integer
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        text:
                          type: string
                        user_id:
                          type: integer
                        created_at:
                          type: string
                          format: datetime
                        updated_at:
                          type: string
                          format: datetime
                      required:
                      - id
                      - text
                      - user_id
                      - created_at
                      - updated_at
                required:
                - items
        '404':
          description: User not found
  "/api/v1/users":
    get:
      summary: User list
      tags:
      - Users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  current_page:
                    type: integer
                  total_pages:
                    type: integer
                  per_page:
                    type: integer
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        email:
                          type: string
                        created_at:
                          type: string
                          format: datetime
                        updated_at:
                          type: string
                          format: datetime
                      required:
                      - id
                      - email
                      - created_at
                      - updated_at
                required:
                - items
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
